language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-7
          packages:
            - clang-7
      env:
        - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-8
          packages:
            - clang-8
      env:
        - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-9
      env:
        - MATRIX_EVAL="CC=clang-9 && CXX=clang++-9"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-10 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-10
      env:
        - MATRIX_EVAL="CC=clang-10 && CXX=clang++-10"
    - os: osx
      osx_image: xcode10.3
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
    - os: osx
      osx_image: xcode11
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
    - os: osx
      osx_image: xcode11.6
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
    - os: osx
      osx_image: xcode12
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
    - os: osx
      osx_image: xcode12.2
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
    - os: osx
      osx_image: xcode12u
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
        coverity_scan:
          project:
            name: "kovacsv/VisualScriptEngine"
          notification_email: viktorkovacs@gmail.com
          build_command_prepend: >-
            cov-configure --compiler g++-9 --comptype g++ --template &&
            mkdir CovBuild && cd CovBuild && cmake -DCMAKE_BUILD_TYPE=Debug ..
          build_command: make
          branch_pattern: coverity_scan
      env:
        - secure: "aUNsXQXL4JZoRpdPkLuOvIzHitW+qu57mgWXL1mwhMSzGD7nMeLKmBChRIdfQm5DWdw+t6qcMgC830Pi6W2plkpgBryK4Rk6gDhlhA7s6lEANdHMTD9hmOcBEz5UWJ0IxRyR6nscEBKrzjku5ct3gOt/B3yCyRsjG5uDsBeggDY28A310ijxjWHS7bGu52ihN/45eCyNXzP3Bq3ogwwWertJDAq2rNkBBnj7ISDQWZ9VMOD6iYSOFWvAXGYM9dW2yJAjHQfdv2I7hEW69LzFZ6WZT4UBoZBSeewoeq81yXVfvnr/y0yqfNHuEHJehjOa3bQFrdKOt2CFIWD/TXpEdnE6ICWIGs8dM1adMkLGpi54UMXXU4FSyDP07xMZhfqKvhjYgbITXSVsGmi+mSVaRMWl9McN3hLI4MKZvx/e6LCyP7QbodHN4VxCGdC79KX0RgSVcJLipGuj/zVtTQ9jqaAkaPa4FnGeY3377QIaDrFxShAVhPOrWcjSqEy0MpqFEI8HBG0WYpEGO3ErqASAwpp/UJ19pbaSzXYjYvZZycTFMOaKIQfm5r+BDD2U7iJD7GFvDOM6ftIsdqbWCOIHwBxfqfmbloKUr7/smu19DUVAdDLDkbfoZwbEjJufyYqQBt+3kocoi6AoiptMpVGwfh5mrXjZ3Ncl+Rv8PRtqxeU="
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - mkdir Build
  - cd Build
  - mkdir Debug
  - cd Debug
  - cmake -DCMAKE_BUILD_TYPE=Debug ../..
  - make
  - make test ARGS="-V"
  - cd ..
  - cd ..
  - cd Build
  - mkdir Release
  - cd Release
  - cmake -DCMAKE_BUILD_TYPE=Release ../..
  - make
  - make test ARGS="-V"
  - cd ..
  - cd ..
  - cd Build
  - mkdir RelWithDebInfo
  - cd RelWithDebInfo
  - cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ../..
  - make
  - make test ARGS="-V"
  - cd ..
  - cd ..
